### ISSUE TITLE
Favorite File marked but no email notification -can you help?

### ISSUE THREAD

**Issue by Elvis2000NC** [fkleon/nextcloud-favourite-share#1]
Maybe you can help me:
I have marked a folder as favorite and checked in my settings under NC “Activities” that I want to receive an email when a file is loaded into this folder. This should happen hourly. Unfortunately I don’t get an email, although the smtp works correctly. I have received a test mail.
![grafik](https://user-images.githubusercontent.com/76623282/103155239-1523ba80-479e-11eb-9fa2-b374a7bfa468.png)

**Comment by fkleon** [comment]
Hi @Elvis2000NC

I'm not sure this is the right place for this question. This is an external tool that just copies all favourited items into a new location via Nextcloud's WebDAV API, it does not change the existing notification behaviour.

If Nextcloud is not able to notify you when a file is added to a favourite folder, you could create a similar tool to send notifications for you - i.e. periodically check for new files via the WebDAV API and send an email when a file was created within the last hour.

**Comment by Elvis2000NC** [comment]
Thanks, ich am a dentist and only nc User. I cannot create sth like this 😀
-------- Ursprüngliche Nachricht --------Von: Frederik Leonhardt <notifications@github.com> Datum: 26.12.20  20:37  (GMT+01:00) An: fkleon/nextcloud-favourite-share <nextcloud-favourite-share@noreply.github.com> Cc: Elvis2000NC <ak@gesundes-lachen.de>, Mention <mention@noreply.github.com> Betreff: Re: [fkleon/nextcloud-favourite-share] Favorite File marked but no email notification -can you help? (#1) 
Hi @Elvis2000NC
I'm not sure this is the right place for this question. This is an external tool that just copies all favourited items into a new location via Nextcloud's WebDAV API, it does not change the existing notification behaviour.
If Nextcloud is not able to notify you when a file is added to a favourite folder, you could create a similar tool to send notifications for you - i.e. periodically check for new files via the WebDAV API and send an email when a file was created within the last hour.

**Comment by fkleon** [comment]
Sounds like this is out of scope for this tool. I suggest you to raise an issue with [Nextcloud](https://github.com/nextcloud/server) directly.
